### ISSUE TITLE
/attendees/:id with an invalid ID should return 404 and not 500

### ISSUE THREAD

**Issue by jtexeira** [cesium/safira#265]
```
2022-02-10T11:56:37.849889+00:00 app[web.1]: 11:56:37.848 [info] GET /api/v1/attendees/79a29c1c-9f2e-4de1-a318-54eb1e6ec060

2022-02-10T11:56:37.864057+00:00 app[web.1]: 11:56:37.863 [info] Sent 500 in 15ms

2022-02-10T11:56:37.865382+00:00 app[web.1]: 11:56:37.863 [info] Converted error :undef to 500 response

2022-02-10T11:56:37.865760+00:00 app[web.1]: 11:56:37.865 [error] #PID<0.3687.0> running SafiraWeb.Endpoint (connection #PID<0.3686.0>, stream id 1) terminated

2022-02-10T11:56:37.865760+00:00 app[web.1]: Server: sei22-staging.herokuapp.com:80 (http)

2022-02-10T11:56:37.865761+00:00 app[web.1]: Request: GET /api/v1/attendees/79a29c1c-9f2e-4de1-a318-54eb1e6ec060

2022-02-10T11:56:37.865761+00:00 app[web.1]: ** (exit) an exception was raised:

2022-02-10T11:56:37.865761+00:00 app[web.1]:     ** (UndefinedFunctionError) function nil.badges/0 is undefined

2022-02-10T11:56:37.865762+00:00 app[web.1]:         nil.badges()

2022-02-10T11:56:37.865762+00:00 app[web.1]:         (safira) lib/safira/accounts/accounts.ex:98: anonymous fn/1 in Safira.Accounts.get_attendee_with_badge_count!/1

2022-02-10T11:56:37.865763+00:00 app[web.1]:         (safira) lib/safira_web/controllers/attendee_controller.ex:17: SafiraWeb.AttendeeController.show/2

2022-02-10T11:56:37.865763+00:00 app[web.1]:         (safira) lib/safira_web/controllers/attendee_controller.ex:1: SafiraWeb.AttendeeController.action/2

2022-02-10T11:56:37.865764+00:00 app[web.1]:         (safira) lib/safira_web/controllers/attendee_controller.ex:1: SafiraWeb.AttendeeController.phoenix_controller_pipeline/2

2022-02-10T11:56:37.865764+00:00 app[web.1]:         (phoenix) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2

2022-02-10T11:56:37.865765+00:00 app[web.1]:         (safira) lib/safira_web/endpoint.ex:1: SafiraWeb.Endpoint.plug_builder_call/2

2022-02-10T11:56:37.865765+00:00 app[web.1]:         (safira) lib/safira_web/endpoint.ex:1: SafiraWeb.Endpoint.call/2
```

**Comment by jtexeira** [comment]
Bug veio do facto de se ter chamado o endpoint com um attendee inexistente
```
sei22-staging::DATABASE=> select * from attendees where id='79a29c1c-9f2e-4de1-a318-54eb1e6ec060';
 nickname | user_id | inserted_at | updated_at | id | volunteer | avatar | name | discord_association_code | discord_id | token_balance | entries 
----------+---------+-------------+------------+----+-----------+--------+------+--------------------------+------------+---------------+---------
(0 rows)
```
Vou mudar o titulo disto para dar um 404 e não um 500
