### ISSUE TITLE
O typo que vai persegir o safira para o resto da sua existencia

### ISSUE THREAD

**Issue by jtexeira** [cesium/safira#266]
```
2022-02-10T11:35:30.904752+00:00 app[web.1]: 11:35:30.904 [info] GET /api/v1/badges

2022-02-10T11:35:30.974950+00:00 app[web.1]: 11:35:30.972 [info] Sent 500 in 67ms

2022-02-10T11:35:30.975042+00:00 app[web.1]: 11:35:30.972 [info] Converted error {:badkey, :start_badge, %Safira.Contest.Badge{__meta__: #Ecto.Schema.Metadata<:loaded, "badges">, attendees: #Ecto.Association.NotLoaded<association :attendees is not loaded>, avatar: %{file_name: "dias(2)(FINAL).png", updated_at: ~N[2022-01-23 17:04:01]}, begin: ~U[2021-02-24 02:00:00Z], begin_badge: ~U[2022-02-03 00:00:00Z], description: "Participa no evento no dia 24 de fevereiro", end: ~U[2021-02-25 02:00:00Z], end_badge: ~U[2022-02-28 00:00:00Z], id: 357, inserted_at: ~N[2022-01-23 17:04:00], name: "Dia 2", referrals: #Ecto.Association.NotLoaded<association :referrals is not loaded>, tokens: 20, type: 3, updated_at: ~N[2022-01-23 17:04:01]}} to 500 response

2022-02-10T11:35:30.975043+00:00 app[web.1]: 11:35:30.973 [error] #PID<0.3525.0> running SafiraWeb.Endpoint (connection #PID<0.3524.0>, stream id 1) terminated

2022-02-10T11:35:30.975043+00:00 app[web.1]: Server: sei22-staging.herokuapp.com:80 (http)

2022-02-10T11:35:30.975044+00:00 app[web.1]: Request: GET /api/v1/badges

2022-02-10T11:35:30.975044+00:00 app[web.1]: ** (exit) an exception was raised:

2022-02-10T11:35:30.975045+00:00 app[web.1]:     ** (KeyError) key :start_badge not found in: %Safira.Contest.Badge{__meta__: #Ecto.Schema.Metadata<:loaded, "badges">, attendees: #Ecto.Association.NotLoaded<association :attendees is not loaded>, avatar: %{file_name: "dias(2)(FINAL).png", updated_at: ~N[2022-01-23 17:04:01]}, begin: ~U[2021-02-24 02:00:00Z], begin_badge: ~U[2022-02-03 00:00:00Z], description: "Participa no evento no dia 24 de fevereiro", end: ~U[2021-02-25 02:00:00Z], end_badge: ~U[2022-02-28 00:00:00Z], id: 357, inserted_at: ~N[2022-01-23 17:04:00], name: "Dia 2", referrals: #Ecto.Association.NotLoaded<association :referrals is not loaded>, tokens: 20, type: 3, updated_at: ~N[2022-01-23 17:04:01]}

2022-02-10T11:35:30.975046+00:00 app[web.1]:         (safira) lib/safira/contest/contest.ex:87: Safira.Contest.badge_is_in_time/1

2022-02-10T11:35:30.975047+00:00 app[web.1]:         (safira) lib/safira/contest/contest.ex:17: anonymous fn/1 in Safira.Contest.list_available_badges/0

2022-02-10T11:35:30.975047+00:00 app[web.1]:         (elixir) lib/enum.ex:3029: Enum.reject_list/2

2022-02-10T11:35:30.975047+00:00 app[web.1]:         (safira) lib/safira_web/controllers/badge_controller.ex:16: SafiraWeb.BadgeController.index/2

2022-02-10T11:35:30.975048+00:00 app[web.1]:         (safira) lib/safira_web/controllers/badge_controller.ex:1: SafiraWeb.BadgeController.action/2

2022-02-10T11:35:30.975048+00:00 app[web.1]:         (safira) lib/safira_web/controllers/badge_controller.ex:1: SafiraWeb.BadgeController.phoenix_controller_pipeline/2

2022-02-10T11:35:30.975049+00:00 app[web.1]:         (phoenix) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2

2022-02-10T11:35:30.975049+00:00 app[web.1]:         (safira) lib/safira_web/endpoint.ex:1: SafiraWeb.Endpoint.plug_builder_call/2
```

**Comment by jtexeira** [comment]
Fixed with commit https://github.com/cesium/safira/commit/ba37e6daabea6f7db0fc6affa11edb10fc948627
